{
 "title": "mysql监控指标dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "mysql_cpu使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "tcloud_database_mysql_CPUUseRate",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "mysql_内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "tcloud_database_mysql_MemoryUseRate",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "mysql_磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "tcloud_database_mysql_VolumeRate",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "mysql每秒执行操作数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tcloud_database_mysql_QPS", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "mysql网络流入流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "tcloud_database_mysql_BytesReceived",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "mysql网络流出流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "tcloud_database_mysql_BytesSent",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "mysql慢查询",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcloud_database_mysql_SlowQueries",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "mysql线程数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcloud_database_mysql_ThreadsConnected",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "mysql查询数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tcloud_database_mysql_Queries", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  }
 ]
}