{
 "title": "mysql监控指标dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "mysql_cpu使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "tcloud_database_mysql_cpu", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "mysql_内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "tcloud_database_mysql_mem", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "mysql_磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "tcloud_database_mysql_disk", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "mysql网络流入流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "tcloud_database_mysql_net_in", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "mysql网络流出流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "tcloud_database_mysql_net_out", "legendFormat": "{{exported_instance}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } }
 ]
}