#mysql:
#  - CPUUseRate
#  - MemoryUseRate
#  - BytesSent
#  - BytesReceived
#  - VolumeRate
#  - QPS
#  - MaxConnections
#  - ThreadsConnected
#  - SlowQueries
#  - Queries
#  - SelectScan
#  - MasterSlaveSyncDistance
#  - SecondsBehindMaster
#  - InnodbCacheUseRate
#  - InnodbCacheHitRate
#  - KeyCacheUseRate
#  - KeyCacheHitRate
#  - ComCommit
#  - ComRollback
#  - ThreadsRunning
#mongodb:
#  - Netin
#  - Netout
#  - Cpuusage
#  - Memusage
#  - Conn
#  - Qr
#  - Qw
#  - Slavedelay
redis:
  - QpsMin
  - CpuUsNodeMin
