mysql:
  - CPUUseRate
  - MemoryUseRate
  - BytesSent
  - BytesReceived
  - VolumeRate
  - QPS
  - MaxConnections
  - ThreadsConnected
  - SlowQueries
  - Queries
  - MasterSlaveSyncDistance
  - SecondsBehindMaster
mongodb:
  - Netin
  - Netout
  - Cpuusage
  - Memusage
  - Conn
